name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test-branch ]
  pull_request:
    branches: [ test-branch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      name: Check out current branch
      with:
        path: local

    - name: Checkout next branch
      uses: actions/checkout@v2
      with:
        ref: test-branch
        path: test
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run test script
      run: |
        pip install gitpython
        python local/helloworld.py local/*.md
